name: "Auto assignment for issues"

on:
  issues:
    types: ["opened"]

jobs:
  auto-assign:
    uses: ./.github/workflows/shared-auto-assign-issues.yml
    secrets:
      token: ${{ secrets.BOT_ACCESS_TOKEN }}
